name: Rust

on:
  push:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      commit:
        description: 'commit id'
        required: true
        default: HEAD
env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target: [ x86_64-unknown-linux-gnu, x86_64-pc-windows-gnu, x86_64-apple-darwin ]
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          default: true
          override: true
          target: ${{ matrix.target }}
          toolchain: stable
      - name: Build
        run: |
         git reset --hard ${{ github.event.inputs.commit }}
         rustc --print target-list
         tree
         if cargo build --target ${{ matrix.target }}; then
           ls -l target/debug
           strip target/debug/jyt
         fi
         ls -l target/debug/build
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.target }}
          if-no-files-found: ignore
          path: target/debug/jyt
